trigger:
  - main

pool:
  vmImage: 'windows-latest'  # Usando un agente de Windows

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g @angular/cli@17
    displayName: 'Install Angular CLI'

  - script: |
      npm install
    displayName: 'Install project dependencies'

  - script: |
      npm run build
    displayName: 'Build the project'

  # Instalar AWS CLI en Windows correctamente
  - script: |
      Invoke-WebRequest "https://awscli.amazonaws.com/AWSCLIV2/latest/AWSCLIV2.msi" -OutFile "AWSCLIV2.msi"
      Start-Process msiexec.exe -ArgumentList '/i', 'AWSCLIV2.msi', '/quiet', '/norestart' -NoNewWindow -Wait
      Remove-Item -Force "AWSCLIV2.msi"
    displayName: 'Install AWS CLI'

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-connection'
      regionName: 'us-east-1'
      awsCommand: 's3'
      awsSubCommand: 'sync'
      awsArguments: './dist/movie-challenge/browser s3://azure-challenge-lab --delete'
    displayName: 'Upload to S3'

  - task: AWSCLI@1
    inputs:
      awsCredentials: 'aws-connection'
      awsCommand: 'cloudfront'
      awsSubCommand: 'create-invalidation'
      awsArguments: '--distribution-id E19BQQB7IQY3QZ paths "/*"'
    displayName: 'Invalidate CloudFront'
